service: ecommerce-app

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  deploymentBucket: 
    name: serverless-deployment-bucket-backend
  environment:
    DB_USERNAME: admin
    DB_PASSWORD: mypassword
    DB_HOST: !GetAtt EcommerceDBInstance.Endpoint.Address
    DB_NAME: ecommerce

custom:
  ec2:
    ami: ami-12345678
    instanceType: t2.micro
    sshKeyName: your-key-pair-name
    securityGroupIds:
      - sg-0123456789abcdef0
    subnetIds:
      - subnet-12345678
resources:
  Resources:
    EC2Instance:
      Type: AWS::EC2::Instance
      Properties:
        InstanceType: t2.micro
        ImageId: ami-00e52cd80f25edd3c
        KeyName: dummy-ec2
        SecurityGroupIds:
          - sg-0278418c7f8c4194b
        SubnetId: subnet-068a6bb11afdaf1d0
        Tags:
          - Key: Name
            Value: BackendAppEC2
    EcommerceDBInstance:
      Type: AWS::RDS::DBInstance
      Properties:
        DBInstanceIdentifier: ecommerce-db
        AllocatedStorage: 20
        DBInstanceClass: db.t3.micro
        Engine: postgres
        EngineVersion: "15.4"
        MasterUsername: ecommerce_admin
        MasterUserPassword: password
        DBName: ecommerce
        PubliclyAccessible: true
        VPCSecurityGroups:
          - sg-0e1dc2e55e3111f86
        BackupRetentionPeriod: 7
